#!/usr/bin/env python3
"""
Post-process shader analyzer raw_data.json and split stage counts into:

- player variant records
- unique subprogram blobs
- unique parameter blobs

This script does not re-parse package data. It only consumes raw_data.json
generated by shader_variant_analyzer.py.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Tuple


def _combo_key(keyword_indices: List[int]) -> Tuple[int, ...]:
    return tuple(sorted(set(int(idx) for idx in keyword_indices)))


def _keyword_names(all_keywords: List[str], keyword_indices: Tuple[int, ...]) -> List[str]:
    names = []
    for idx in keyword_indices:
        if 0 <= idx < len(all_keywords):
            names.append(all_keywords[idx])
        else:
            names.append(f"?{idx}")
    return names


def _compute_stats(subs: List[Dict]) -> Dict[str, int]:
    return {
        "player_variant_records": len(subs),
        "unique_subprogram_blobs": len({sp["blob_index"] for sp in subs if sp.get("blob_index", -1) >= 0}),
        "unique_parameter_blobs": len(
            {sp["parameter_blob_index"] for sp in subs if sp.get("parameter_blob_index", -1) >= 0}
        ),
    }


def _build_stage_stats(shader_name: str, shader_keywords: List[str], subshader_index: int, pass_index: int, pass_data: Dict,
                       stage: str, subs: List[Dict]) -> Dict:
    combo_groups = defaultdict(list)
    for sp in subs:
        combo_groups[_combo_key(sp.get("keyword_indices", []))].append(sp)

    stage_stats = _compute_stats(subs)
    stage_stats["keyword_combo_count"] = len(combo_groups)

    combos = []
    sorted_combos = sorted(
        combo_groups.items(),
        key=lambda item: (-len(item[1]), _keyword_names(shader_keywords, item[0]))
    )
    for keyword_indices, combo_subs in sorted_combos:
        combo_stats = _compute_stats(combo_subs)
        combos.append({
            "keyword_indices": list(keyword_indices),
            "keyword_names": _keyword_names(shader_keywords, keyword_indices),
            **combo_stats,
        })

    return {
        "shader_name": shader_name,
        "subshader_index": subshader_index,
        "pass_index": pass_index,
        "pass_name": pass_data.get("name") or "(unnamed)",
        "stage": stage,
        "platforms": pass_data.get("platforms", []),
        **stage_stats,
        "combos": combos,
    }


def analyze(raw_data: Dict, shader_name_filter: str = "") -> Dict:
    results = {
        "source": raw_data.get("source", ""),
        "shader_count": 0,
        "stages": [],
    }

    target_name = shader_name_filter.strip().lower()

    for shader in raw_data.get("shaders", []):
        shader_name = shader.get("name", "")
        if target_name and shader_name.lower() != target_name:
            continue

        results["shader_count"] += 1
        shader_keywords = shader.get("keywords", [])
        for subshader_index, subshader in enumerate(shader.get("sub_shaders", [])):
            for pass_index, pass_data in enumerate(subshader.get("passes", [])):
                programs = pass_data.get("programs", {})
                for stage, subs in programs.items():
                    if not subs:
                        continue
                    results["stages"].append(
                        _build_stage_stats(
                            shader_name,
                            shader_keywords,
                            subshader_index,
                            pass_index,
                            pass_data,
                            stage,
                            subs,
                        )
                    )

    results["stages"].sort(
        key=lambda item: (
            item["shader_name"],
            item["subshader_index"],
            item["pass_index"],
            item["stage"],
        )
    )
    return results


def _write_markdown(results: Dict, output_path: Path) -> None:
    lines: List[str] = []
    lines.append("# Variant Record Stats")
    lines.append("")
    if results.get("source"):
        lines.append(f"- Source: `{results['source']}`")
    lines.append(f"- Shader count: `{results['shader_count']}`")
    lines.append(f"- Stage count: `{len(results['stages'])}`")
    lines.append("")

    current_shader = None
    for stage_info in results["stages"]:
        shader_name = stage_info["shader_name"]
        if shader_name != current_shader:
            current_shader = shader_name
            lines.append(f"## `{shader_name}`")
            lines.append("")

        lines.append(
            f"### SubShader {stage_info['subshader_index']} / Pass {stage_info['pass_index']}: "
            f"{stage_info['pass_name']} / {stage_info['stage']}"
        )
        lines.append("")
        lines.append(f"- Player variant records: `{stage_info['player_variant_records']:,}`")
        lines.append(f"- Unique subprogram blobs: `{stage_info['unique_subprogram_blobs']:,}`")
        lines.append(f"- Unique parameter blobs: `{stage_info['unique_parameter_blobs']:,}`")
        lines.append(f"- Keyword combo count: `{stage_info['keyword_combo_count']:,}`")
        if stage_info["platforms"]:
            lines.append(f"- Platforms: `{', '.join(str(v) for v in stage_info['platforms'])}`")
        lines.append("")
        lines.append("| # | Keyword Combo | Player Records | Unique Subprogram Blobs | Unique Parameter Blobs |")
        lines.append("|---|--------------|----------------|-------------------------|------------------------|")
        for idx, combo in enumerate(stage_info["combos"], 1):
            combo_name = ", ".join(combo["keyword_names"]) if combo["keyword_names"] else "(no keywords)"
            lines.append(
                f"| {idx} | `{combo_name}` | {combo['player_variant_records']:,} | "
                f"{combo['unique_subprogram_blobs']:,} | {combo['unique_parameter_blobs']:,} |"
            )
        lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Split shader analyzer counts into records and unique blobs.")
    parser.add_argument("raw_data", help="Path to raw_data.json generated by shader_variant_analyzer.py")
    parser.add_argument("-o", "--output-dir", help="Output directory. Defaults to raw_data.json parent directory")
    parser.add_argument("--shader-name", default="", help="Only emit one shader by exact name")
    args = parser.parse_args()

    raw_path = Path(args.raw_data)
    output_dir = Path(args.output_dir) if args.output_dir else raw_path.parent
    output_dir.mkdir(parents=True, exist_ok=True)

    raw_data = json.loads(raw_path.read_text(encoding="utf-8"))
    results = analyze(raw_data, shader_name_filter=args.shader_name)

    json_path = output_dir / "variant_record_stats.json"
    md_path = output_dir / "variant_record_stats.md"
    json_path.write_text(json.dumps(results, indent=2, ensure_ascii=False), encoding="utf-8")
    _write_markdown(results, md_path)

    print(f"Generated: {md_path}")
    print(f"Generated: {json_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
